/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Input: typeof import('./../src/components/form/Input/index.vue')['default']
    LayoutFooter: typeof import('./../src/components/layout/LayoutFooter.vue')['default']
    LayoutGroup: typeof import('./../src/components/layout/LayoutGroup.vue')['default']
    LayoutHeader: typeof import('./../src/components/layout/LayoutHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchField: typeof import('./../src/components/form/SearchField/index.vue')['default']
  }
}
