// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./../components/article/src/ArticleCard.vue')['default']
    ArticleList: typeof import('./../components/article/src/ArticleList.vue')['default']
    NavMenu: typeof import('./../components/menu/src/NavMenu.vue')['default']
    NavSubMenu: typeof import('./../components/menu/src/NavSubMenu.vue')['default']
    Pager: typeof import('./../components/pager/src/Pager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
